razonyang/hugo-theme-bootstrap

assets/css/app.css, layouts/_default/single.html, layouts/partials/post-toc.html, src/scss/main.scss
=> Add post TOC partial

exampleSite/config/_default/menu.en.toml, exampleSite/config/_default/menu.zh-hant.toml, exampleSite/config/_default/menu.zh.toml, exampleSite/content/archives/_index.md, exampleSite/content/archives/_index.zh-hant.md, exampleSite/content/archives/_index.zh.md, layouts/_default/archive.html
=> Feature archive

exampleSite/config/_default/params.toml, layouts/partials/head.html, layouts/partials/site-verification.html
=> Add site verification partial

exampleSite/config/_default/config.toml, layouts/robots.txt
=> Add support for robots.txt

layouts/404.html, layouts/_default/baseof.html, layouts/_default/list.html, layouts/_default/single.html, layouts/_default/terms.html, layouts/index.html
=> Feature 404

exampleSite/content/posts/shortcodes/alert.md, layouts/shortcodes/alert.html
=> Feature shortcode alert

layouts/partials/post.html, layouts/partials/post/related-posts.html
=> Display related posts

README.md, README.zh-CN.md, README.zh-TW.md
我在使用快速开始文档时，新建的文章位置在posts目录下，才能显示在首页上
=> modify start document

i18n/ru.toml, i18n/uz.toml
Two language files added:
- Russian;
- Uzbek language;
=> New languages

exampleSite/config/_default/config.toml, exampleSite/config/_default/languages.toml, exampleSite/config/_default/menu.fr.toml, exampleSite/config/_default/params.fr.toml, exampleSite/content/fr/archives/_index.md, exampleSite/content/fr/categories/_index.md, exampleSite/content/fr/posts/_index.md, exampleSite/content/fr/posts/emoji-support.md, exampleSite/content/fr/posts/markdown-syntax.md, exampleSite/content/fr/posts/math-typesetting.md, exampleSite/content/fr/posts/placeholder-text.md, exampleSite/content/fr/posts/rich-content.md, exampleSite/content/fr/posts/shortcodes/_index.md, exampleSite/content/fr/posts/shortcodes/alert.md, exampleSite/content/fr/posts/shortcodes/bilibili.md, exampleSite/content/fr/posts/shortcodes/codepen.md, exampleSite/content/fr/posts/shortcodes/iqiyi.md, exampleSite/content/fr/posts/shortcodes/jsfiddle.md, exampleSite/content/fr/posts/shortcodes/jsrun.md, exampleSite/content/fr/posts/shortcodes/neteasemusic.md, exampleSite/content/fr/posts/shortcodes/tencentvideo.md, exampleSite/content/fr/posts/shortcodes/youku.md, exampleSite/content/fr/search/_index.md, exampleSite/content/fr/series/_index.md, exampleSite/content/fr/tags/_index.md, i18n/fr.toml
Add french language and the possibility to ignore one or more language.
=> Add lang FR and Ignore one or more language

README.md, README.zh-CN.md, README.zh-TW.md, exampleSite/config/_default/social.toml, layouts/partials/footer/social-links.html
This adds support for Kaggle as a social link.
=> Add the Kaggle social link

i18n/de.toml, i18n/en.toml, layouts/partials/post/meta.html
I'd assume there are people not understanding icons, so I added titles.
What do you think about it?
=> feat: added titles to post-meta data

layouts/partials/post/meta.html
=> feat: localize time and dates

README.md, README.zh-CN.md, README.zh-TW.md, exampleSite/config/_default/params.toml, layouts/partials/header/search-bar.html, layouts/partials/header/social-share.html
added options to enable/disable parts of the menu bar to get a bit more space
defaults are enabled, so nothing really changed
added params to config
=> make search-bar and social-share configurable

USERS.md
Add yshalsager.com to the list
=> chore: update USERS.md

layouts/_default/baseof.html
this might be a fix of https://github.com/razonyang/hugo-theme-bootstrap/issues/317
=> appending data-palette attribute to <html> tag

layouts/partials/footer/social-links.html, layouts/partials/sidebar/profile/meta.html
=> fix(social-links): missing RSS link

layouts/partials/header/settings/actions.html
=> feat: add the go back button

layouts/partials/helpers/image.html
=> fix: cannot render SVG images

layouts/partials/sidebar/recent-posts.html
=> fix: recent posts widget

layouts/partials/post/excerpt.html
=> fix: post excerpt

layouts/partials/docs/catalog.html
=> fix(docs-catalog): invalid CSS/JS selector

exampleSite/content/docs/configuration/index.md, exampleSite/content/docs/configuration/index.zh-cn.md, exampleSite/content/docs/configuration/index.zh-tw.md, layouts/partials/post/related-posts.html, layouts/partials/sidebar/featured-posts.html, layouts/partials/sidebar/recent-posts.html
=> Feature 374

layouts/partials/sidebar/recent-posts.html
=> fix(post): recent posts order

layouts/partials/head/meta/social.html
=> fix: social image meta tag

assets/js/code/code-block.ts
=> fix(code-block): correct maxLines parameter

exampleSite/content/docs/installation/hugo-module/index.md, exampleSite/content/docs/installation/hugo-module/index.zh-cn.md, exampleSite/content/docs/installation/hugo-module/index.zh-tw.md
| Type | Message |
|:---|:---|
| Documentation | `docs: Added install sub-step to specify theme.` |
Fixed #454.
=> Add sub-step to switch theme

layouts/partials/docs/post.html, layouts/partials/post.html, layouts/partials/post/featured-image.html
=> feat: show the featured image at the begining of content

exampleSite/config/_default/params.toml, exampleSite/content/docs/configuration/index.md, exampleSite/content/docs/configuration/index.zh-cn.md, exampleSite/content/docs/configuration/index.zh-tw.md, layouts/partials/post/featured-image.html
=> feat(post): add the post.featuredImage parameter

exampleSite/content/docs/content/index.md, exampleSite/content/docs/content/index.zh-cn.md, exampleSite/content/docs/content/index.zh-tw.md
=> Typo ture -> true

i18n/de.toml
=> Add missing word "All" to de.toml

assets/main/scss/_config.scss, assets/main/scss/_sidebar.scss, exampleSite/config/_default/params.toml, exampleSite/content/docs/configuration/index.md, exampleSite/content/docs/configuration/index.zh-cn.md, exampleSite/content/docs/configuration/index.zh-tw.md
Fixing sidebar on non-docs layouts via `sidebar.fixed` parameter:
```toml
[sidebar]
fixed = true
```
Related issues #404, #461
=> feat: add the sidebar.fixed parameter for fixing the sidebar

assets/main/scss/_config.scss, exampleSite/config/_default/params.toml, exampleSite/content/docs/configuration/index.md, exampleSite/content/docs/configuration/index.zh-cn.md, exampleSite/content/docs/configuration/index.zh-tw.md
```toml
breadcrumbDivider = ">"
```
=> feat: add the breadcrumbDivider parameter

assets/main/scss/index.scss, layouts/partials/assets/main/css.html
=> fix(rtlcss): separate CSS into LTR and RTL

assets/main/scss/_config.scss, assets/main/scss/post/_toc.scss, assets/main/scss/post/index.scss, exampleSite/config/_default/params.toml, exampleSite/content/docs/configuration/index.md, exampleSite/content/docs/configuration/index.zh-cn.md, exampleSite/content/docs/configuration/index.zh-tw.md
=> Feat post toc style type

layouts/partials/header/index.html, postcss.config.js
=> fix: dropdown menu out of screen on fullWidth

layouts/_default/_markup/render-image.html, layouts/partials/helpers/image.html
=> feat: display the title attribute on image

layouts/partials/post/meta.html
=> feat: sort taxonomies by title

exampleSite/config/_default/params.toml, exampleSite/content/docs/configuration/index.md, exampleSite/content/docs/configuration/index.zh-cn.md, exampleSite/content/docs/configuration/index.zh-tw.md, layouts/partials/head/title.html, layouts/partials/post/meta.html
=> feat: add the taxonomySortingMethod parameter

assets/search/search.ts, layouts/_default/search.html, layouts/index.json
=> feat(search): use the same thumbnail as post list does

assets/search/search.ts, assets/viewer/js/index.ts
=> fix(viewer): display the images on search results

assets/icons/index.js, layouts/_default/_markup/render-link.html, layouts/partials/docs/catalog.html
=> feat: show the external icon next the external link

i18n/id.toml
I already discus to adding this new language in #549.
=> feat(i18n): Added Indonesian Language

i18n/id.toml
=> feat(i18n): Fix untranslated

exampleSite/config/_default/params.toml, exampleSite/content/docs/advanced/hooks/index.md, exampleSite/content/docs/advanced/hooks/index.zh-cn.md, exampleSite/content/docs/advanced/hooks/index.zh-tw.md, exampleSite/content/docs/layouts/contact-form/index.md, exampleSite/content/docs/layouts/contact-form/index.zh-cn.md, exampleSite/content/docs/layouts/contact-form/index.zh-tw.md, layouts/_default/contact.html, layouts/partials/contact/fields.html, layouts/partials/contact/file.html, layouts/partials/contact/form-body.html, layouts/partials/contact/form-netlify.html, layouts/partials/contact/form.html, layouts/partials/contact/recaptcha.html, layouts/partials/contact/submit.html, postcss.config.js
=> Add contact hooks and reCaptcha widget

assets/bootstrap/template.js, assets/js/font-size-selector/index.ts, assets/js/local-storage/index.ts, assets/js/mode/index.ts, assets/js/palettes/index.ts, assets/js/sidebar-toggle/index.ts, assets/main/js/utterances.ts, layouts/partials/assets/main/js.html
=> Fix localstorage

layouts/partials/header/font-size.html, layouts/partials/header/theme.html
=> fix: replace non-linkable dropdown item with button

layouts/index.xml
=> fix(rss): replace copyright {year} placeholder with this year

exampleSite/config/_default/params.toml, exampleSite/content/docs/configuration/site-params/index.md, exampleSite/content/docs/configuration/site-params/index.zh-cn.md, exampleSite/content/docs/configuration/site-params/index.zh-tw.md, exampleSite/content/docs/image-processing/index.md, exampleSite/content/docs/image-processing/index.zh-cn.md, exampleSite/content/docs/image-processing/index.zh-tw.md, layouts/_default/_markup/render-image.html, layouts/partials/helpers/image.html
=> feat: add the post.imageTitleAsCaption parameter for showing image title as caption

assets/main/js/utterances.ts
=> fix(utterances): correct theme on the auto color mode

assets/main/scss/post/index.scss, layouts/_default/_markup/render-heading.html
=> feat: show heading anchors on hover

layouts/partials/header/search-bar.html
=> fix: correct search bar action

assets/main/scss/post/_toc.scss, layouts/partials/docs/post.html, layouts/partials/post.html
=> feat: apply scrollspy to table of contents

assets/main/scss/_top-app-bar.scss, assets/main/scss/_variables-theme.scss, exampleSite/content/docs/advanced/scss-variables/index.md, exampleSite/content/docs/advanced/scss-variables/index.zh-hans.md, exampleSite/content/docs/advanced/scss-variables/index.zh-hant.md, exampleSite/layouts/shortcodes/code/scss-options.html
Now, you can disable the logo animation via the `$logo-animation` option.
```scss
// assets/main/scss/_variables.scss
$logo-animation: false;
```
Fixed #639.
=> feat(scss): add the $logo-animation option

i18n/de.toml
chore(i18n): add font sizes and noscript information to de.toml
=> chore(i18n): add font sizes and noscript information to de.toml

assets/search/engine.ts
=> Performance: improve search speed

assets/main/scss/post/index.scss, exampleSite/content/docs/shortcodes/alert/index.md, exampleSite/content/docs/shortcodes/alert/index.zh-hans.md, exampleSite/content/docs/shortcodes/alert/index.zh-hant.md, exampleSite/layouts/shortcodes/code/alert-with-markdown-example.html, exampleSite/layouts/shortcodes/config/markup-goldmark-renderer-unsafe.html, layouts/shortcodes/code-toggle.html
=> Make alert icon and the first paragraph inline

exampleSite/content/docs/shortcodes/media/index.md, layouts/shortcodes/asciinema.html
```markdown
{{< asciinema 514468 >}}
```
=> Add the asciinema shortcode

assets/search/engine.ts, assets/search/search.ts, layouts/_default/search.html, layouts/partials/search/loading.html
=> fix(search): loading spinner

i18n/en.toml, i18n/zh-cn.toml, i18n/zh-hans.toml, i18n/zh-hant.toml, i18n/zh-hk.toml, i18n/zh-tw.toml, layouts/partials/search/sidebar.html, layouts/partials/sidebar/stats.html
=> feat: add the stats widget

exampleSite/content/docs/advanced/purgecss/index.md
Here's a small typo fix.
Thank you for this amazing Hugo template.
=> docs: fixed typo in PurgeCSS configuration note

exampleSite/config/production/params.toml, layouts/partials/assets/google-adsense.html, layouts/partials/body-end.html, layouts/partials/head/assets.html
=> chore: move Google AdSense script into <head>

exampleSite/content/authors/rubonnek/_index.md, exampleSite/content/docs/deployment/gitlab-pages/index.md, exampleSite/content/docs/deployment/overview/index.md, exampleSite/layouts/shortcodes/code/deployment-gitlab-pages-ci.html
Add Gitlab Pages deployment example.
=> docs: add Gitlab Pages deployment example

assets/js/mode/index.ts
=> fix: avoid flickering on the case of `color=dark`

exampleSite/layouts/shortcodes/code/deployment-gitlab-pages-ci.html
Documentation cleanup following up on https://github.com/razonyang/hugo-theme-bootstrap-skeleton/commit/c938c4cf1ef3a29c47d4b3ff89d90b341f9469ef
=> docs: remove unnecessary Gitlab CI hugo command

assets/main/scss/_code.scss, assets/main/scss/_variables-theme.scss, exampleSite/layouts/shortcodes/code/scss-options.html
Select `<code>` content on click, except code block
=> feat: add the $code-select SCSS variable, default to true

USERS.md, i18n/id.toml
* Invalid translation to Indonesian language for `[reading_time]`.
* Add another website that use this theme.
=> Fix id.toml Typo and update USERS.md

exampleSite/config/_default/params.toml, exampleSite/content/docs/configuration/site-params/index.md, exampleSite/content/docs/configuration/site-params/index.zh-hans.md, exampleSite/content/docs/configuration/site-params/index.zh-hant.md, layouts/partials/docs/post.html, layouts/partials/post.html, layouts/partials/post/content.html, layouts/partials/post/excerpt.html
Read more from content after clicking the read more button if enabled
Fixed #693.
=> feat: add the post.readMoreFromContent parameter

layouts/partials/post/content.html
=> fix: do not show non-manual splitting summary

exampleSite/config/_default/params.toml, exampleSite/content/docs/configuration/site-params/index.md, exampleSite/content/docs/configuration/site-params/index.zh-hans.md, exampleSite/content/docs/configuration/site-params/index.zh-hant.md, layouts/partials/assets/plausible-analytics/js.html, layouts/partials/head/assets.html
=> feat: add support for Plausible Analytics

layouts/index.json
=> fix: Do not attempt to resize SVGs

exampleSite/content/docs/configuration/page-params/index.md, exampleSite/content/docs/configuration/page-params/index.zh-hans.md, exampleSite/content/docs/configuration/page-params/index.zh-hant.md, layouts/_default/archives.html, layouts/_default/contact.html, layouts/_default/list.html, layouts/_default/search.html, layouts/_default/single.html, layouts/_default/terms.html, layouts/docs/list.html, layouts/docs/single.html, layouts/partials/docs/sidebar.html, layouts/partials/post/panel/sidebar-toggler.html, layouts/partials/sidebar.html
=> feat: add the sidebar page parameter

exampleSite/content/docs/layouts/landing/index.md, exampleSite/content/docs/layouts/landing/index.zh-hans.md, exampleSite/content/docs/layouts/landing/index.zh-hant.md, layouts/landing/list.html, layouts/landing/single.html, layouts/shortcodes/text/align-center.html, layouts/shortcodes/text/align-end.html, layouts/shortcodes/text/align-start.html, layouts/shortcodes/text/capitalize.html, layouts/shortcodes/text/lowercase.html, layouts/shortcodes/text/uppercase.html, layouts/shortcodes/text/user-select-all.html, layouts/shortcodes/text/user-select-none.html
=> Feature: landing page layout

exampleSite/config/_default/params.toml, exampleSite/content/docs/configuration/site-params/index.md, exampleSite/content/docs/configuration/site-params/index.zh-hans.md, exampleSite/content/docs/configuration/site-params/index.zh-hant.md, layouts/partials/sidebar/taxonomies-toggle.html
=> feat: add the site parameter sidebar.taxonomiesToggleArchives

exampleSite/content/posts/diagram/index.md
=> docs: update the Diagram page

assets/search/engine.ts, exampleSite/config/_default/params.toml, layouts/partials/assets/search/js.html
=> feat: add more Fuse.js options

assets/search/engine.ts, assets/search/meta.json, assets/search/search.ts, exampleSite/config/_default/params.toml, exampleSite/content/docs/layouts/search/index.md, exampleSite/content/docs/layouts/search/index.zh-hans.md, exampleSite/content/docs/layouts/search/index.zh-hant.md, layouts/partials/assets/search/head.html, layouts/partials/assets/search/js.html, layouts/partials/head/assets.html, layouts/partials/search/index.json, layouts/partials/search/meta.json
=> Search index performance

layouts/index.json
=> fix(search): empty the layouts.index.json for backward compatible

assets/search/engine.ts
=> fix(search): validate the taxonomies' existence before formatting search index

assets/search/engine.ts, layouts/partials/head/favicons.html
=> Bugfix favicon

assets/main/scss/_icons.scss, assets/mermaid/js/options.ts, exampleSite/assets/icons/custom.js, exampleSite/content/posts/diagram/index.md
=> Fix Mermaid icons

assets/main/scss/_config.scss
=> fix: use with instead of isset to avoid the warning message

layouts/partials/helpers/social-links.html
=> feat: use rel=me instead on social links

layouts/_default/baseof.html, layouts/alias.html, layouts/partials/functions/color.html
Currently, the page will be flickering on the case of redirecting.
https://hbs.razonyang.com/v1/en/about-us/
=> Avoid flickering when redirect

assets/main/scss/_social-links.scss, assets/main/scss/index.scss, layouts/partials/header/social-links.html, layouts/partials/helpers/social-links.html
=> style: color the social links icons

assets/main/js/index.ts, layouts/partials/post/toc-wrapper.html
=> fix: output the TOC inside post content if the sidebar is disabled

layouts/partials/sidebar/profile/meta.html
=> style: align profile texts and icons

i18n/en.toml, i18n/zh-cn.toml, i18n/zh-hans.toml, i18n/zh-hant.toml, i18n/zh-hk.toml, i18n/zh-tw.toml, layouts/404.html, layouts/_default/offline.html
=> style: update offline/404 information and icon color

assets/js/iframe/index.ts, assets/main/js/index.ts, exampleSite/content/docs/shortcodes/game/index.md, exampleSite/content/docs/shortcodes/game/index.zh-hans.md, exampleSite/content/docs/shortcodes/game/index.zh-hant.md, exampleSite/content/docs/shortcodes/iframe/index.md, exampleSite/content/docs/shortcodes/iframe/index.zh-hans.md, exampleSite/content/docs/shortcodes/iframe/index.zh-hant.md, i18n/en.toml, i18n/zh-cn.toml, i18n/zh-hans.toml, i18n/zh-hant.toml, i18n/zh-hk.toml, i18n/zh-tw.toml, layouts/shortcodes/game.html, layouts/shortcodes/iframe.html
=> feat: add the iframe shortcode and improve the game shortcode

assets/main/scss/_pagination.scss
=> fix: adjust pagination style to the upstream changes

exampleSite/content/docs/configuration/page-params/index.md, exampleSite/content/docs/configuration/page-params/index.zh-hans.md, exampleSite/content/docs/configuration/page-params/index.zh-hant.md, layouts/partials/search/index.json
=> feat: add the `index` page parameter for indexing the page in client search engine or not

layouts/partials/footer/social-links.html
=> style: update footer social links

assets/algolia/js/index.ts, assets/algolia/scss/index.scss, exampleSite/.gitignore, layouts/partials/algolia/index.json
1. Press <kbd>CTRL</kbd> +<kbd>K</kbd> to show the search box.
2. Press <kbd>ESC</kbd> to hide the search box.
3. Allow arrows keys to navigate the results, <kbd>ENTER</kbd> for selecting item.
=> feat(algolia): add keybord navigation and shortcuts

i18n/de.toml
Updated and revised some strings.
=> fix: update german translation

USERS.md
bronski.net now uses PaperMod theme
Fixed #.
=> Remove bronski.net

exampleSite/package-lock.json, exampleSite/package.json, package.hugo.json
=> Bootstrap v5.3.0 alpha1

exampleSite/content/docs/look-and-feel/index.md, exampleSite/content/docs/look-and-feel/index.zh-hans.md, exampleSite/content/docs/look-and-feel/index.zh-hant.md, exampleSite/layouts/shortcodes/code/look-and-feel-favicon-sizes.html, layouts/partials/functions/favicon.html, layouts/partials/head/favicons.html, layouts/partials/pwa/manifest.json
Allow changing icon sizes by favicon.sizes
Support favicon.webp and it will get higher priority if present
Fixed #845
=> Add the favicon parameter and support favicon with webp format

exampleSite/content/docs/configuration/menu/index.md, exampleSite/content/docs/configuration/page-params/index.md, exampleSite/content/docs/configuration/page-params/index.zh-hans.md, exampleSite/content/docs/configuration/page-params/index.zh-hant.md, layouts/partials/functions/featured-img-alt.html, layouts/partials/head/meta/social.html, layouts/partials/post/featured-image.html
=> feat: add the `featuredImageAlt` page parameter

.prettierrc, assets/main/scss/_nav.scss, exampleSite/content/docs/shortcodes/toggle/index.en.md, layouts/shortcodes/toggle-item.html, layouts/shortcodes/toggle.html, package-lock.json, package.json
=> feat: add the toggle shortcode

layouts/partials/post/related-posts.html, layouts/partials/sidebar/featured-posts.html, layouts/partials/sidebar/main.html, layouts/partials/sidebar/posts-toggle.html, layouts/partials/sidebar/recent-posts.html
=> Fix `relatedPostCount`, `featuredPostCount` and `recentPostCount` page parameters

assets/js/mode/index.ts
=> fix: initialize script on the case of disabling color toggle

layouts/partials/docs/nav.html, layouts/partials/footer/actions-panel.html, layouts/partials/header/index.html
=> seo: avoid using headings tag on offcanvas titles

layouts/partials/head.html
=> fix: the description meta tag

assets/js/slide/index.ts, assets/main/js/index.ts, assets/main/scss/_slide.scss, assets/main/scss/index.scss, assets/main/scss/post/_card.scss, assets/main/scss/post/index.scss, layouts/partials/post/card-img.html, layouts/partials/post/card.html, layouts/partials/post/related-posts.html
=> feat: add the slide component and use it on related posts

assets/main/scss/_breadcrumb.scss, assets/main/scss/index.scss, layouts/partials/breadcrumb.html
=> style: do not wrap the breadcrumb on small screens

README.md, exampleSite/layouts/partials/hooks/footer-end.html
Add the Digital Ocean logo at the end of pages
=> chore: add Digital Ocean as a sponsor

layouts/partials/functions/featured-img.html, layouts/partials/functions/page-images.html, layouts/partials/functions/thumbnail.html
=> fix(thumbnail): find featured images and thumbnails by type: image

layouts/partials/body-end.html, layouts/partials/head/assets.html
=> chore: move Google Analytics script to <head>

layouts/partials/staticman/form-body.html
=> fix(staticman): correct the form layout

i18n/de.toml
=> chore(i18n): update de.toml

layouts/partials/assets/search/meta.html
=> fix: generate search index meta even if search.indexPreload is false

i18n/es.toml
=> Adds Spanish i18n

assets/main/scss/_palettes.scss, exampleSite/package-lock.json, exampleSite/package.json, package.hugo.json
Fix the palette background colors.
=> fix: adjust to Bootstrap v5.3.1

i18n/en.toml, i18n/zh-cn.toml, i18n/zh-hans.toml, i18n/zh-hant.toml, i18n/zh-hk.toml, i18n/zh-tw.toml, layouts/partials/post/panel/comments.html, layouts/partials/post/panel/copyright.html, layouts/partials/post/panel/sidebar-toggler.html, layouts/partials/post/panel/toc.html, layouts/partials/post/panel/translations.html
=> fix(i18n): translate more UI items

layouts/partials/assets/google-analytics.html
=> fix(google-analytics): drop the deprecated template

config.toml, exampleSite/content/docs/configuration/site-params/index.md, exampleSite/content/docs/configuration/site-params/index.zh-hans.md, exampleSite/content/docs/configuration/site-params/index.zh-hant.md, layouts/partials/carousel.html
=> Allow configuring the number of posts of homepage carousel

layouts/partials/archives/list.html
=> fix(archives): correct the dateFormat parameter

i18n/ru.toml
Hello. I apologize if the message is not in the correct format.
I offer my own version of Russian language support. Translated as closely as possible to the meaning in the context of the site.
The result of the work can be viewed on [my website](https://sudakov.spb.ru/)
=> Translation

exampleSite/content/docs/configuration/page-params/index.md, exampleSite/content/docs/configuration/page-params/index.zh-hans.md, exampleSite/content/docs/configuration/page-params/index.zh-hant.md, layouts/_default/_markup/render-heading.html
=> feat: add the numberifyHeadings page parameter

i18n/ar.toml, i18n/de.toml, i18n/en.toml, i18n/es.toml, i18n/fr.toml, i18n/id.toml, i18n/ja.toml, i18n/pl.toml, i18n/pt.toml, i18n/ru.toml, i18n/uk.toml, i18n/uz.toml, i18n/zh-cn.toml, i18n/zh-hans.toml, i18n/zh-hant.toml, i18n/zh-hk.toml, i18n/zh-tw.toml, layouts/partials/docs/nav.html
modified:   i18n/ru.toml
modified:   i18n/en.toml
modified:   layouts/partials/docs/nav.html
Hello. It caught my eye when I created the section with documents. No translation into other languages.
Thanks for your work :o)
=> 	modified:  3 files for multilingual support

layouts/partials/head/title.html
=> fix: do not paginate on page

i18n/uk.toml
=> chore(i18n): Update Ukrainian localization file

assets/js/code/index.ts, assets/main/scss/_code.scss
style: set max-height for code block to partially avoid CLS issue
Fixes #1049
=> fix: code block maxlines not working all the time

assets/js/sidebar-toggle/index.ts, assets/main/init/index.ts, assets/main/scss/_sidebar.scss, assets/templates/staticman/comments.html, exampleSite/config/_default/params.toml, exampleSite/content/docs/content/index.md, exampleSite/content/docs/content/index.zh-hans.md, exampleSite/content/docs/content/index.zh-hant.md, layouts/_default/baseof.html, layouts/docs/list.html, layouts/docs/single.html, layouts/partials/assets/main/init-js.html
=> fix: sidebar toggle CLS issue

assets/main/scss/_sidebar.scss, exampleSite/content/docs/content/index.md, exampleSite/content/docs/content/index.zh-hans.md, exampleSite/content/docs/content/index.zh-hant.md, layouts/_default/single.html, layouts/docs/single.html, layouts/landing/single.html, layouts/partials/functions/container-class.html
=> fix: broken layouts

assets/main/scss/_sidebar.scss, assets/templates/staticman/comments.html, layouts/_default/baseof.html, layouts/partials/functions/container-class.html
=> fix: correct sidebar, header and footer layouts when enabling sidebar.fixed

layouts/partials/docs/doc-nav.html, layouts/partials/docs/post.html
=> fix: broken previous doc link and next doc link

i18n/de.toml
| Type | Message |
|:---|:---|
| Bug Fix | `fix: fixed german translations and typos` |
Fixed #1086 .
=> resolves Issue 1086:  fixed translations and typos

assets/icons/icons/faCodeberg.js, assets/icons/icons/index.js, assets/icons/index.js, exampleSite/config/_default/params.toml, exampleSite/content/docs/widgets/social-links/index.md, exampleSite/content/docs/widgets/social-links/index.zh-hans.md, exampleSite/content/docs/widgets/social-links/index.zh-hant.md, i18n/ar.toml, i18n/de.toml, i18n/en.toml, i18n/es.toml, i18n/fr.toml, i18n/id.toml, i18n/ja.toml, i18n/pl.toml, i18n/pt.toml, i18n/ru.toml, i18n/uk.toml, i18n/uz.toml, i18n/zh-cn.toml, i18n/zh-hans.toml, i18n/zh-hant.toml, i18n/zh-hk.toml, i18n/zh-tw.toml, layouts/partials/helpers/social-links.html
=> feat: add support for Codeberg social link

exampleSite/content/docs/shortcodes/online-ide/index.md, hugo.toml, layouts/_default/terms.html, layouts/partials/docs/list.html, layouts/partials/list.html, layouts/partials/pagination.html, layouts/partials/wrap-pagination.html, netlify.toml
deps: require Hugo v0.146.5 or later
Closes #1136
=> fix: replace `template` syntax with `partial` for pagination

exampleSite/content/docs/widgets/social-links/index.md
For me personally, it is easier to search for a specific platform in the documentation if the table is sorted.
That is why I have sorted the table in this PR.
| Type | Message |
|:---|:---|
| Documentation | `docs: Just sorted the table of the platforms. ` |
Fixed #1139.
=> Update docs: Sort Table
