i18n/de.toml
i18n/en.toml
layouts/partials/helpers/image.html
layouts/partials/post/meta.html

Add support for resizing images using Hugos [Image processing](https://gohugo.io/content-management/image-processing/) to get smaller image sizes.
Edit: Forgot to mention that this works only for [pageResources](https://gohugo.io/content-management/page-resources/). When an image is not found as pageResource it will not resize it just style it as earlier.
I have tried testing it with different cases and it seems to work, but I don't know if there is some case which doesn't work.

Resize images

---

exampleSite/config/_default/params.toml
exampleSite/config/production/params.toml
layouts/partials/head.html
layouts/partials/head/meta.html
layouts/partials/head/meta/robots.html

HTML Meta Tag "robots" is useful for SEO, and this could we steered very easy using Page/Global Params.

Feature: Added possibility to stear meta robots tag

---

exampleSite/config/_default/markup.toml

**Example site, [Markdown Syntax Guide](https://hbs.razonyang.com/en/posts/markdown-syntax/):**
Last chapter `Other Elements — abbr, sub, sup, kbd, mark`
Terms like H<sub>2</sub>O are rendered incorrectly since by default, hugo's default renderer `goldmark` scrubs raw html tags for security reasons (see hugo's [documentation](https://gohugo.io/getting-started/configuration-markup#goldmark) on this topic). This PR corrects this incorrect rendering.

Example site: correct rendering of subscript, superscript and other raw html markup

---

layouts/partials/docs/catalog.html
layouts/partials/sidebar/profile/meta.html

This feature allows specifying the text of link to the content, the `Title` will be used if the `linkTitle` is not set. It's useful that if you want to make the link text shorter. Of course, you could change the title directly, but it'll make the title ambiguous on list pages and SEO results.
Content:
```toml
// docs/installation/_index.md
title = "Installation"
// docs/installation/git-submodule.md
title = "Install via Git Submodule"
linkTitle = "Git Submodule"
// docs/installation/go-module.md
title = "Install via Go Module"
linkTitle = "Go Module"
```
Catalog:
```text
Installation
- Git Submodule
- Go Module
```

Feature link title

---

assets/main/scss/index.scss

This PR is useful for users who don't use the FAQ layout at all, the CSS bundle size will be reduces by about `5.5kB`.

Performance: make FAQ CSS purgeable

---

assets/js/code/code-block.ts
assets/main/scss/_code.scss
postcss.config.js

Now, the code block will display the `title` attribute on the bottom.
<pre>
```toml {title="config/_default/params.toml"}
mainSections = ["blog", "posts", "docs", "notes"]
```
</pre>

feat(code-block): display the title attribute

---

assets/viewer/js/index.ts
layouts/partials/helpers/image.html
layouts/partials/post/reward.html
layouts/partials/sidebar/profile/avatar.html

Images with the `data-viewer-invisible` attribute will be filtered by the image viewer. It allows users excluding custom images from the image viewer.
```html
```

feat(image-viewer): add the data-viewer-invisible attribute for image tag

---

i18n/ar.toml
i18n/en.toml
i18n/zh-cn.toml
i18n/zh-hk.toml
i18n/zh-tw.toml
layouts/partials/sidebar/taxonomies.html

Taxonomies "all" button link was missing from internationalization.

fix: Add missing 'all' word to i18n

---

layouts/partials/docs/repo.html

Fixes https://github.com/razonyang/hugo-theme-bootstrap/issues/475

fix(docs-repo): use the correct contentDir when custom one is set

---

layouts/partials/helpers/image.html

Close #470, it works only on the images placed on `static` folder.

feat: look up modern formats for images with the same filename

---

assets/main/scss/post/index.scss
exampleSite/config/_default/params.toml
exampleSite/content/docs/configuration/index.md
exampleSite/content/docs/configuration/index.zh-cn.md
exampleSite/content/docs/configuration/index.zh-tw.md
layouts/partials/docs/toc.html
layouts/partials/post.html
layouts/partials/sidebar/main.html
layouts/partials/sidebar/toc.html

Fixed #382.
This PR adds a new parameter called `tocPosition`. You can move the TOC inside the post content by setting `tocPosition = "content"`. It only affects on `posts`'s layout.

Feature: add parameter `tocPosition`.

---

README.md
assets/main/scss/_config.scss
assets/main/scss/post/index.scss
exampleSite/config/_default/params.toml
exampleSite/content/docs/configuration/index.md
exampleSite/content/docs/configuration/index.zh-cn.md
exampleSite/content/docs/configuration/index.zh-tw.md

Added the `post.numberifyHeadings` parameter.
```toml
[post]
numberifyHeadings = true # Count headings automatically.
```
Relative to #501.

feat: numberify headings

---

exampleSite/config/_default/params.toml
exampleSite/content/docs/configuration/index.md
exampleSite/content/docs/configuration/index.zh-cn.md
exampleSite/content/docs/configuration/index.zh-tw.md
layouts/_default/archive.html
layouts/partials/sidebar/archive.html
layouts/partials/sidebar/main.html

feat: add the archive widget

---

exampleSite/config/_default/params.toml
exampleSite/content/docs/configuration/site-params/index.md
exampleSite/content/docs/configuration/site-params/index.zh-cn.md
exampleSite/content/docs/configuration/site-params/index.zh-tw.md
layouts/partials/sidebar/archive-items.html
layouts/partials/sidebar/archive.html
layouts/partials/sidebar/main.html
layouts/partials/sidebar/taxonomies-toggle.html
layouts/partials/sidebar/taxonomies.html

Add the taxonomies toggle for saving sidebar space.
Disable previous categories, tags, series and archives widget by default.
If you want to use the previous widgets, just enable them in `params.toml`:
```toml
[sidebar]
archives = true # Enable archives widget
taxonomiesToggle = false # Disable taxonomy toggle
categories = true # Enable categories widget
tags = true # Enable tags widget
series = true # Enable series widget
```

feat: add the taxonomies toggle widget

---

exampleSite/config/_default/params.toml
exampleSite/content/docs/configuration/page-params/index.md
exampleSite/content/docs/configuration/page-params/index.zh-cn.md
exampleSite/content/docs/configuration/page-params/index.zh-tw.md
exampleSite/content/docs/configuration/site-params/index.md
exampleSite/content/docs/configuration/site-params/index.zh-cn.md
exampleSite/content/docs/configuration/site-params/index.zh-tw.md
layouts/partials/docs/post.html
layouts/partials/post.html
layouts/partials/post/nav.html

Feat post nav

---

layouts/partials/post/thumbnail.html

feat: add the width and height for thumbnails

---

assets/js/giscus/index.ts
assets/js/mode/index.ts
assets/js/mode/prefer.ts
assets/js/utterances/index.ts
exampleSite/config/_default/params.toml
exampleSite/content/docs/configuration/site-params/index.md
exampleSite/content/docs/configuration/site-params/index.zh-hans.md
exampleSite/content/docs/configuration/site-params/index.zh-hant.md
exampleSite/content/docs/getting-started/introduction/index.md
exampleSite/content/docs/getting-started/introduction/index.zh-hans.md
exampleSite/content/docs/getting-started/introduction/index.zh-hant.md
exampleSite/content/docs/widgets/comments/index.md
exampleSite/content/docs/widgets/comments/index.zh-hans.md
exampleSite/content/docs/widgets/comments/index.zh-hant.md
layouts/partials/assets/main/js.html
layouts/partials/post/comments.html
layouts/partials/post/comments/giscus.html

Add suppport for Giscus comments engine

---

assets/main/scss/post/index.scss

| Type | Message |
|:---|:---|
| Bug Fix | `fix: incorrect table of contents count` |
Fixed #619.

Fix Headings Counter

---

assets/main/scss/_config.scss
assets/main/scss/_palettes.scss
assets/main/scss/_top-app-bar.scss
exampleSite/config/_default/params.toml
exampleSite/content/docs/configuration/site-params/index.md
exampleSite/content/docs/configuration/site-params/index.zh-hans.md
exampleSite/content/docs/configuration/site-params/index.zh-hant.md

```toml
[topAppBar]
coloredInDark = true # Colored in dark mode
```
Fixed #627.

feat: add the topAppBar.coloredInDark parameter

---

layouts/partials/header/social-links.html

fix: Fixes the broken social links navigation under 1200px device width. The nav element was wider than the parent li element.

Fix the social links nav (header)

---

assets/main/scss/_search.scss
assets/search/languages.ts
assets/search/search.ts
assets/search/templates/result.html
exampleSite/content/docs/advanced/hooks/index.md
exampleSite/content/docs/advanced/hooks/index.zh-hans.md
exampleSite/content/docs/advanced/hooks/index.zh-hant.md
exampleSite/layouts/partials/hooks/search/sidebar-end.html
exampleSite/layouts/partials/hooks/sidebar-begin.html
i18n/en.toml
i18n/zh-cn.toml
i18n/zh-hans.toml
i18n/zh-hant.toml
i18n/zh-hk.toml
i18n/zh-tw.toml
layouts/_default/search.html
layouts/partials/search/form.html
layouts/partials/search/index.json
layouts/partials/search/sidebar.html
layouts/partials/sidebar/search-form.html
purgecss.config.js

1. Allow searching all pages regardless of their languages.
2. Allow filtering result by language, author, category, tag and series.
3. Add search sidebar and some hooks: `search/sidebar-begin` and `search/sidebar-end`.
4. Redesign the search page UI.
5. Add the search form widget.

Add Advanced Search Options

---

assets/search/engine.ts
assets/search/form.ts
i18n/en.toml
i18n/zh-cn.toml
i18n/zh-hans.toml
i18n/zh-hant.toml
i18n/zh-hk.toml
i18n/zh-tw.toml
layouts/partials/search/form.html
layouts/partials/search/index.json

feat(search): add sorting support

---

assets/search/engine.ts
layouts/partials/search/index.json

For example: tag `'CSS 'HTML | 'Alert` matches tags that start with `CSS` and `HTML`, OR start with `Alert`.
See also [extended search](https://fusejs.io/examples.html#extended-search).

feat(search): allow filtering results via taxonomies with AND, OR operations

---

assets/js/toc/index.ts
assets/main/js/index.ts
assets/main/scss/post/_toc.scss
exampleSite/assets/main/scss/_custom.scss
exampleSite/config/_default/params.toml
exampleSite/content/docs/configuration/site-params/index.md
exampleSite/content/docs/configuration/site-params/index.zh-hans.md
exampleSite/content/docs/configuration/site-params/index.zh-hant.md
layouts/_default/archives.html
layouts/_default/contact.html
layouts/_default/single.html
layouts/_default/terms.html
layouts/docs/list.html
layouts/docs/single.html
layouts/index.html
layouts/partials/docs/post.html
layouts/partials/docs/repo.html
layouts/partials/post.html
layouts/partials/post/toc-wrapper.html
layouts/partials/sidebar.html
layouts/partials/sidebar/archive.html
layouts/partials/sidebar/featured-posts.html
layouts/partials/sidebar/posts-toggle.html
layouts/partials/sidebar/profile/compact.html
layouts/partials/sidebar/profile/default.html
layouts/partials/sidebar/recent-posts.html
layouts/partials/sidebar/stats.html
layouts/partials/sidebar/taxonomies-toggle.html
layouts/partials/sidebar/taxonomies.html
layouts/partials/sidebar/toc.html

See #687.
> The `tocPosition` may be removed in the later version.

UX: display TOC above content on small screens and DO NOT collapse sidebar widgets by default.

---

layouts/index.html

Following up on #709. It seems that the home page is missing the sidebar parameter.
Related issue: #708

fix: include the sidebar page parameter in the home page

---

exampleSite/content/docs/widgets/comments/index.md
exampleSite/content/docs/widgets/comments/index.zh-hans.md
exampleSite/content/docs/widgets/comments/index.zh-hant.md

Update documentation now that email is not a required field on the client side if configured that way.
[Also siteKey needs to be a string](https://github.com/eduardoboucas/staticman/blob/5d7ed7708775e3d4864382cca88d2d73ff875864/siteConfig.js#L182-L184). At least my staticman instance complained about it being an "object" if the empty string is not specified in `staticman.yml`.

docs: fix requiredFields and empty siteKey for staticman.yml

---

exampleSite/content/posts/diagram/index.md
layouts/_default/_markup/render-codeblock-mermaid.html
layouts/partials/assets/diagram/js.html

This PR adds support for mermaid code blocks using [hugo's Markdown render hooks](https://gohugo.io/templates/render-hooks/#render-hooks-for-code-blocks).
This PR also simplifies the use of mermaid diagrams inside a page: once a `mermaid` code block or shortcode is found on the page, mermaid is loaded/enabled automatically.
**Note:** Latest mermaid version is 9.1.7, while the theme still uses version 8.14.0. Maybe this can be addressed, too. The same is true for KaTeX: latest version is 0.16.3, while HBS theme still uses 0.15.2.

feat: add support for mermaid code blocks

---

README.md
netlify.toml

This PR updates `hugo`, `go` and `npm` versions when deploying to Netlify.

Chore: netlify deployment: update to latest npm, go and hugo versions

---

assets/service-worker/routes/page.ts

fix: use NetworkFirst strategy in order to avoid loading nonexistent assets

---

exampleSite/content/docs/configuration/page-params/index.md
exampleSite/content/docs/configuration/page-params/index.zh-hans.md
exampleSite/content/docs/configuration/page-params/index.zh-hant.md

I stumbled upon a missing title in my front matter and noticed it was missing in your documentation.
I hope this PR is okay -- I usually look at your documentation before I look at the official documentation

docs: Add missing `title` Page parameter

---

exampleSite/content/docs/content/index.md
exampleSite/content/docs/content/index.zh-hans.md
exampleSite/content/docs/content/index.zh-hant.md
layouts/_default/terms.html
layouts/partials/author/avatar.html
layouts/partials/author/meta.html
layouts/partials/author/profile.html
layouts/partials/author/social.html
layouts/partials/list.html

This PR changes the author style and accepts the page parameter `social.email` for generating Gravatar avatar if there is no avatar image resource.
Desktop
Mobile

style: change authors list

---

layouts/partials/functions/toc.html
layouts/partials/post/panel/toc.html
layouts/partials/post/toc-wrapper.html
layouts/partials/post/toc.html
layouts/partials/sidebar/toc.html

fix: correct the TOC if conditions

---

exampleSite/layouts/partials/hooks/docs/nav-begin.html
layouts/partials/docs/nav.html
layouts/partials/header/brand.html
layouts/partials/header/index.html

style(top-app-bar): align the brand and logo to center on small screen

---

assets/main/scss/_search.scss

fix: display the search bar icon on focus

---

assets/main/scss/post/_panel.scss
layouts/partials/post/panel.html
layouts/partials/post/panel/translations.html

style: change the post panel design

---

exampleSite/content/docs/layouts/contact/index.md
exampleSite/content/docs/layouts/contact/index.zh-hans.md
exampleSite/content/docs/layouts/contact/index.zh-hant.md

It would be nice to mention that the contact form also works with a [Formailer](https://github.com/djatwood/formailer) instance as its endpoint, which is a self-hosted alternative.

docs: mention Formailer also works as a contact form endpoint

---

assets/main/scss/post/index.scss
layouts/_default/_markup/render-heading.html

The anchor symbol was always in RSS feeds:
>Heading§
Now that is no longer the case:
>Heading
These changes preserve the anchor functionality, but remove the symbols where they are not needed.

fix: anchor symbols not in feed

---

assets/search/engine.ts
exampleSite/config/_default/params.toml
exampleSite/content/docs/layouts/search/index.md
exampleSite/content/docs/layouts/search/index.zh-hans.md
exampleSite/content/docs/layouts/search/index.zh-hant.md
layouts/partials/assets/search/meta.html

Fixed #850 
This PR limits the results up to `100` by default, it makes sense in most cases.

feat: add the `search.maxResults` parameter to limit the returned search results

---

assets/js/search/index.ts
assets/main/js/index.ts
assets/main/scss/_top-app-bar.scss
exampleSite/config/_default/params.toml
exampleSite/content/docs/layouts/search/index.md
exampleSite/content/docs/layouts/search/index.zh-hans.md
exampleSite/content/docs/layouts/search/index.zh-hant.md
i18n/en.toml
i18n/zh-cn.toml
i18n/zh-hans.toml
i18n/zh-hant.toml
i18n/zh-hk.toml
i18n/zh-tw.toml
layouts/partials/functions/search-input-placeholder.html
layouts/partials/header/search-bar.html
layouts/partials/search/form.html

Add the search shortcut

---

archetypes/default.md
exampleSite/config/_default/params.toml
exampleSite/content/docs/widgets/funding/index.md
exampleSite/content/docs/widgets/funding/index.zh-hans.md
exampleSite/content/docs/widgets/funding/index.zh-hant.md
exampleSite/content/docs/widgets/reward/index.md
exampleSite/content/docs/widgets/reward/index.zh-hans.md
exampleSite/content/docs/widgets/reward/index.zh-hant.md
i18n/en.toml
i18n/zh-cn.toml
i18n/zh-hans.toml
i18n/zh-hant.toml
i18n/zh-hk.toml
i18n/zh-tw.toml
layouts/partials/post/panel.html
layouts/partials/post/panel/funding.html

feat: add the funding widget

---

assets/main/scss/_palettes.scss
layouts/partials/header/palettes.html

fix: remove invalid HTML from palette dropdown menu

---

exampleSite/content/docs/image-processing/index.md
layouts/_default/_markup/render-image.html
layouts/partials/helpers/image.html
layouts/shortcodes/clearfix.html

Related discussion https://github.com/razonyang/hugo-theme-bootstrap/discussions/895#discussioncomment-4811410

Fix floating images and add clearfix shortcode

---

exampleSite/package-lock.json
exampleSite/package.json
layouts/_default/_markup/render-codeblock-mermaid.html
layouts/shortcodes/mermaid.html
package.hugo.json

This PR bumps mermaid to latest version 10.0.0. It also reflects that MermaidJS now specifies to write chart's markdown within a `pre` HTML tag to improve semantics.

Chore: bump mermaid to latest version

---

assets/main/scss/_main.scss
assets/main/scss/_reboot.scss
layouts/partials/header.html
layouts/partials/header/index.html

There are some issues and limitations of the fixed header.
1. Hard to append custom code to the beginning of  `<body>`.
2. The `main-begin` hook sucks.

fix: replace fixed position with sticky for header

---

layouts/partials/sidebar/taxonomies.html

fix(sidebar-taxonomies): add the missing HTML tag

---

exampleSite/content/posts/placeholder-text/index.md
layouts/_default/baseof.html
layouts/partials/helpers/social-links.html

I'm currently implementing a [content security policy](https://infosec.mozilla.org/guidelines/web_security#content-security-policy) header for my site and stumbled upon some violations related to certain resources being fetched through `http`  instead of `https`.
This PR attempts to mitigate that issue -- I'm not sure if all of the changes I've made are required.
As an additional note, I started working on this after scanning my site through the [Mozilla Observatory](https://observatory.mozilla.org/).

chore: use https when fetching/referencing external resources

---

exampleSite/content/docs/configuration/site-params/index.md
exampleSite/content/docs/configuration/site-params/index.zh-hans.md
exampleSite/content/docs/configuration/site-params/index.zh-hant.md
exampleSite/content/docs/content/index.md
exampleSite/content/docs/content/index.zh-hans.md
exampleSite/content/docs/content/index.zh-hant.md
exampleSite/content/docs/getting-started/introduction/index.md
exampleSite/content/posts/markdown-syntax/index.md
layouts/partials/docs/post.html
layouts/partials/post.html
layouts/partials/post/excerpt.html

BREAKING CHANGE: remove the post.excerpt parameter
```yaml
---
description: Post description
---
```

style: show the description if set

---

layouts/partials/header/search-bar.html

style: align the search bar to middle of the header

---

assets/main/scss/_top-app-bar.scss
layouts/partials/header/search-bar.html

Switch back to medium input form size
Tweak the search shortcuts
Expand the input field when typing

style: tweak search bar

---

exampleSite/content/docs/look-and-feel/index.md
exampleSite/content/docs/look-and-feel/index.zh-hans.md
exampleSite/content/docs/look-and-feel/index.zh-hant.md
i18n/ru.toml

modified:   exampleSite/content/docs/look-and-feel/index.md
modified:   exampleSite/content/docs/look-and-feel/index.zh-hans.md
modified:   exampleSite/content/docs/look-and-feel/index.zh-hant.md
modified:   i18n/ru.toml
Hello. :slightly_smiling_face:
While busy adding and changing the color of icons, I noticed some inaccuracies in the instructions and my own translation error.
I wrote a short post about icons that will give you an understanding of what I encountered: [https://sudakov.spb.ru](https://sudakov.spb.ru/blog/%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%BA%D0%BE%D0%BD%D0%BE%D0%BA-%D0%B2-%D0%BC%D0%B5%D0%BD%D1%8E-%D1%82%D0%B5%D0%BC%D1%8B-hbs/)
Where there should be quotes, they are not visible in the documentation. The quotes must be exactly like this, …

	Where there should be quotes, they are not visible in the documentation.

---

layouts/partials/docs/repo.html

Fix a bug in the repository widget where it creates a link with backslashes instead of forward slashes when running hugo on windows

Fix Bug in Repo Widget for Windows computers

---

exampleSite/content/docs/configuration/menu/index.md
exampleSite/content/docs/configuration/menu/index.zh-hans.md
exampleSite/content/docs/configuration/menu/index.zh-hant.md

Fix broken link to the documentation for menu properties on Hugo site.

docs: Fix broken link to the documentation for menu properties on Hugo site.

---

layouts/partials/head/title.html

This patch avoid generating useless pagination pages which may cause performance issues on large site.

fix: avoid paginating on non pagination pages

---

config.toml
exampleSite/config/_default/params.toml
exampleSite/content/docs/configuration/site-params/index.md
exampleSite/content/docs/configuration/site-params/index.zh-hans.md
exampleSite/content/docs/configuration/site-params/index.zh-hant.md
layouts/partials/docs/nav.html

When `false`, do not reduce the font size of children navigation
Fixes #1045.

feat: add the docsNav.reduceFontSize parameter

---

assets/main/scss/docs/index.scss
layouts/partials/docs/nav.html

style: tweak active docs nav item border color

---

layouts/partials/docs/doc-nav.html
layouts/partials/docs/nav.html

fix: sorting docs navigation items in LinkTitle rather than Title
Closes #1130

fix: allow using negative number as navWeight
